version: "3"

services:
  orion-test:
    build:
      context: .
      dockerfile: dev.orion-test.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./orion-test/src:/orion-test/src
      - ./orion-test/test:/orion-test/test
    restart: always

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: oriontest_db
    volumes:
     - ./data/postgres-db:/var/lib/postgresql/data

#  mongo:
#    image: mongo
#    restart: always
#   volumes:
#     - ./data/mongo-db:/data/db
#    ports:
#      - "27017:27017"
