export const CONFIG_ENV_OPTIONS_REGISTER_AS = 'envOptions';
export const CONFIG_WS_OPTIONS_REGISTER_AS = 'wsOptions';
export const CONFIG_INFURA_OPTIONS_SERVICE_REGISTER_AS = 'infuraOptions';
export const CONFIG_BINANCE_OPTIONS_SERVICE_REGISTER_AS = 'binanceOptions';
export const WEB3_PROVIDER_ID = 'WEB3_PROVIDER_ID';
export const INTERVAL_HARVEST_TRANSACTIONS_SEC = 1000 * 15; // Each 15 sec.
export const HTTP_REQUEST_TIMEOUT_MSEC = (1000 * 30); // 30 sec.
export const BINANCE_FETCH_CANDLES_INTERVAL = '1m';
export const BINANCE_FETCH_CANDLES_TIMESHIFT_MSEC = (1000 * 60) * 10; // 10 min.
export const BINANCE_FETCH_CANDLES_LIMIT = 30;
export const CURRENCY_TIMESHIFT_AS_FRESH_SEC = 60 * 10; // Latest 10 min.
